name: "jeandle-llvm check"

on:
  pull_request_target:
    types: [ opened, synchronize, reopened, labeled, unlabeled ]
    branches:
      - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test-linux-x64:
    name: linux-x64
    uses: ./.github/workflows/test-linux.yml
    with:
      runs-on: ubuntu-22.04
      target: X86

  test-linux-aarch64:
    name: linux-aarch64
    uses: ./.github/workflows/test-linux.yml
    with:
      runs-on: ubuntu-22.04-arm
      target: AArch64
    if: ${{ contains(github.event.pull_request.labels.*.name, 'AArch64') }}

  test-linux-riscv64:
    uses: ./.github/workflows/test-linux.yml
    with:
      runs-on: riscv-builders
      target: RISCV
    if: ${{ contains(github.event.pull_request.labels.*.name, 'RISC-V') }}

  clang-format:
    name: "clang-format check"
    runs-on: ubuntu-22.04
    steps:
      - name: 'checkout the source code'
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 1
      - name: clang-format
        run : |
          git remote add jeandle-main https://github.com/jeandle/jeandle-llvm.git
          git fetch --depth=1 jeandle-main
          sudo apt-get install -y clang-format
          git clang-format jeandle-main/main
          if [ -n "$(git status --porcelain)" ]; then
            echo "Format check failed!"
            exit 1
          else
            exit 0
          fi
