name: 'Test (linux)'

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      target:
        required: true
        type: string

jobs:
  test:
    name: test
    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: 'checkout the source code'
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 1

      - name: build and test
        run : |
          mkdir build
          cd build
          cmake -G "Unix Makefiles" -DLLVM_TARGETS_TO_BUILD=${{ inputs.target }} -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_BUILD_LLVM_DYLIB=ON -DLLVM_DYLIB_COMPONENTS=all ../llvm
          make check-llvm -j $[$(nproc)/2]
